version: "3.8"

services:
  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/auth-service
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret
      - JWT_ACCESS_EXPIRY=3600
      - JWT_REFRESH_EXPIRY=604800
      - CLIENT_URL=http://localhost:3000
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false
      - COOKIE_SAME_SITE=lax
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=user@example.com
      - EMAIL_PASSWORD=your_email_password
      - EMAIL_FROM=noreply@referralnetworkhub.com
      - PASSWORD_RESET_RATE_LIMIT=5
    depends_on:
      - mongo

volumes:
  mongo-data:
# # version: "3.8"

# services:
#   # MongoDB
#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

#   # Auth Service
#   auth-service:
#     build:
#       context: ./auth-service
#       dockerfile: Dockerfile
#     environment:
#       - PORT=3001
#       - MONGODB_URI=mongodb://mongo:27017/auth-service
#       - JWT_SECRET=your_jwt_secret
#       - JWT_REFRESH_SECRET=your_refresh_secret
#     volumes:
#       - ./auth-service:/app
#       # - ./tsconfig.json:/app/tsconfig.json
#     depends_on:
#       - mongo

# volumes:
#   mongo-data:
